# Generated by Django 3.1.2 on 2021-07-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=25)),
                ('regularity', models.CharField(max_length=25)),
                ('complexity', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(default='127.0.0.1', max_length=15)),
                ('action', models.CharField(default='visit', max_length=15)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('country_ip', models.CharField(default='Unknown', max_length=30)),
                ('city_ip', models.CharField(default='Unknown', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('grade', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField()),
                ('error_class', models.CharField(blank=True, max_length=60, null=True)),
                ('error_number', models.CharField(blank=True, max_length=60, null=True)),
                ('error_unit', models.CharField(blank=True, max_length=60, null=True)),
                ('error_type', models.CharField(blank=True, max_length=60, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_grade.character')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_grade.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='gender_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender_zh_hans',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='character_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='character_zh_hans',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='complexity_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='complexity_zh_hans',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='regularity_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='regularity_zh_hans',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
