# Generated by Django 3.2.6 on 2021-12-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=25)),
                ('character_zh_hans', models.CharField(max_length=25, null=True)),
                ('character_en', models.CharField(max_length=25, null=True)),
                ('regularity', models.CharField(max_length=25)),
                ('regularity_zh_hans', models.CharField(max_length=25, null=True)),
                ('regularity_en', models.CharField(max_length=25, null=True)),
                ('complexity', models.CharField(max_length=25)),
                ('complexity_zh_hans', models.CharField(max_length=25, null=True)),
                ('complexity_en', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(default='127.0.0.1', max_length=15)),
                ('action', models.CharField(default='visit', max_length=15)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('country_ip', models.CharField(default='Unknown', max_length=30)),
                ('city_ip', models.CharField(default='Unknown', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('grade', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('gender_zh_hans', models.CharField(max_length=25, null=True)),
                ('gender_en', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField()),
                ('error_class', models.CharField(blank=True, max_length=60, null=True)),
                ('error_class_zh_hans', models.CharField(blank=True, max_length=60, null=True)),
                ('error_class_en', models.CharField(blank=True, max_length=60, null=True)),
                ('error_number', models.CharField(blank=True, max_length=60, null=True)),
                ('error_number_zh_hans', models.CharField(blank=True, max_length=60, null=True)),
                ('error_number_en', models.CharField(blank=True, max_length=60, null=True)),
                ('error_unit', models.CharField(blank=True, max_length=60, null=True)),
                ('error_unit_zh_hans', models.CharField(blank=True, max_length=60, null=True)),
                ('error_unit_en', models.CharField(blank=True, max_length=60, null=True)),
                ('error_type', models.CharField(blank=True, max_length=60, null=True)),
                ('error_type_zh_hans', models.CharField(blank=True, max_length=60, null=True)),
                ('error_type_en', models.CharField(blank=True, max_length=60, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_grade.character')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_grade.student')),
            ],
        ),
    ]
