# Generated by Django 3.1.2 on 2021-07-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grade', '0002_auto_20210712_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='error_class_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='error_class_zh_hans',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='error_number_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='error_number_zh_hans',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='error_type_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='error_type_zh_hans',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='error_unit_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='error_unit_zh_hans',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
