# Generated by Django 3.2.6 on 2021-08-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grade', '0004_alter_response_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
